'use client'
import {Roboto} from "next/font/google";
import "./globals.css";
import Header from "./_components/Header.jsx";
import Footer from "./_components/Footer";
import  {CartContext} from './_context/CartContext'
import {
  ClerkProvider} from '@clerk/nextjs'
import { useState } from "react";

const inter = Roboto({subsets:["latin"], weight:"700"})
/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {
  const [cart,setCart]=useState([])
  return (
    <ClerkProvider>
    <CartContext.Provider value={{cart,setCart}} >
    <html lang="en">
      <body className={`${inter.variable} ${inter.variable} antialiased bg-white`}>
        <Header/>
        {children}
       <Footer/>
      </body>
    </html>
    </CartContext.Provider>
    </ClerkProvider>
  );
}
